# .github/workflows/sync-to-hf.yml
name: Sync to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo $HF_TOKEN | huggingface-cli login --token-stdin
      
      - name: Sync repository to Hugging Face Space
        run: |
          # Create a temporary directory for synchronization
          mkdir -p /tmp/hf-sync
          cp -r * /tmp/hf-sync/ 2>/dev/null || true
          cp -r .github /tmp/hf-sync/ 2>/dev/null || true
          
          # Push files to HF Space using the CLI
          huggingface-cli upload kserumaga/luganda-trainer /tmp/hf-sync/* --repo-type=space