# .github/workflows/sync-to-hf.yml
name: Sync to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Setting up Hugging Face credentials"
          
          # Use the token explicitly with the git protocol
          git remote add hf https://kserumaga:$HF_TOKEN@huggingface.co/spaces/kserumaga/luganda-trainer
          
          # Alternatively, use the newer credential helper approach
          git config --global credential.helper store
          echo "https://kserumaga:$HF_TOKEN@huggingface.co" > ~/.git-credentials
          
          echo "Pushing to Hugging Face Space"
          git push hf main