# .github/workflows/sync-to-hf.yml
name: Sync to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Hugging Face CLI
        run: pip install --upgrade huggingface_hub
      
      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Use the correct login syntax - it changed from huggingface-cli to huggingface-cli login
          echo $HF_TOKEN | huggingface-cli login
      
      - name: Sync repository to Hugging Face Space
        run: |
          # Create a temporary directory for synchronization
          mkdir -p /tmp/hf-sync
          
          # Copy all files (including hidden ones)
          cp -r . /tmp/hf-sync/
          
          # Debug: List what we're about to upload
          echo "Files to be uploaded:"
          ls -la /tmp/hf-sync/
          
          # Push files to HF Space using the newer API
          # The command has changed from huggingface-cli upload to huggingface-cli upload-folder
          huggingface-cli upload-folder --repo-id=kserumaga/luganda-trainer --repo-type=space /tmp/hf-sync/