# .github/workflows/sync-to-hf.yml
name: Sync to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Push to Hugging Face
        uses: huggingface/huggingface-github-action@main
        with:
          command: >-
            git clone https://kserumaga:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/kserumaga/luganda-trainer &&
            rm -rf luganda-trainer/.* luganda-trainer/* &&
            find . -mindepth 1 -maxdepth 1 ! -name "luganda-trainer" | xargs -I{} cp -r {} luganda-trainer/ &&
            cd luganda-trainer && 
            git config user.email "actions@github.com" &&
            git config user.name "GitHub Actions" &&
            git add . &&
            git commit -m "Sync with GitHub repo" &&
            git push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}