# .github/workflows/sync-to-hf.yml
name: Sync to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Verify the directory contents before pushing
          ls -la
          
          # Use the explicit URL with the correct Space name (trainer not translator)
          git remote add hf https://kserumaga:$HF_TOKEN@huggingface.co/spaces/kserumaga/luganda-trainer
          
          # Verbose output to see any errors
          git push -v hf main:main || echo "Push failed with status $?"